#+title: Org Zettelkasten Manual
#+subtitle: Release {{{version}}}
#+author: Yann Herklotz
#+language: en

#+texinfo: @insertcopying

* Introduction
:PROPERTIES:
:DESCRIPTION: Getting started.
:END:
#+cindex: introduction

Niklas Luhmann’s Zettelkasten is becoming increasingly popular for being a great
note taking technique.  However, it is often misunderstood as taking notes
without any structure, whereas Luhmann actually structured his notes
hierarchically, but also allowed for arbitrary links between notes.  Org
Zettelkasten tries to following the general note-taking workflow that Luhmann
used by using as much of Emacs' built-in Org as possible.

** Inserting new notes
#+cindex: notes

There are several possible notes that can be inserted into the Zettelkasten, but
the need for them should arise naturally and one therefore does not have to
think about the separate types of notes directly.  For references I usually use
the fantastic [[https://joostkremers.github.io/ebib/][ebib]] package.

*** Permanent Notes
#+cindex: notes

Inserting new notes into the Zettelkasten can be done for any new piece of
information one wants to permanently add to the tree of notes and therefore the
network of notes.  These are therefore called “permanent notes,” however, these
are not the only notes that may appear in the network.  The most important thing
to take into consideration is that “permanent notes” should be completely in
your own words, and express an idea that also links to other parts in the
network.  At the start it may be necessary to create a few topics that these
notes fit into, however, eventually one should be able to find notes that are
similar enough which this new note should follow.

*** Index notes
#+cindex: notes

Apart from that, there can also be “index notes,” which try to give some
structure to a subsection that may have gotten lost with all of the branches
that may have been added.  In addition to that, these may tie in other notes
from other topics as well that relate to that topic.  These can therefore just
be added whenever you feel like there are too many notes for a subtopic and
cannot keep track of all the possible links.

* GNU Free Documentation License
:PROPERTIES:
:APPENDIX: t
:DESCRIPTION: The license for this documentation.
:END:

#+include: fdl.org

* Main Index
:PROPERTIES:
:INDEX:    cp
:DESCRIPTION: An index of Org Zettelkasten concepts and features.
:END:

* Copying
:PROPERTIES:
:copying: t
:END:

This manual is for Org Zettelkasten version {{{version}}}.

Copyright \copy 2022  Yann Herklotz.

#+begin_quote
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being "A GNU Manual,"
and with the Back-Cover Texts as in (a) below.  A copy of the license
is included in the section entitled "GNU Free Documentation License."

(a) The FSF's Back-Cover Text is: "You have the freedom to copy and
modify this GNU manual."
#+end_quote

* Export Setup :noexport:

#+setupfile: doc-setup.org

#+export_file_name: org-zettelkasten.texi

#+texinfo_dir_category: Zettelkasten
#+texinfo_dir_title: Org Zettelkasten
#+texinfo_dir_desc: A Zettelkasten mode leveraging Org
